# Change these first
owner: MoonlightStudiosInt # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Waddle Penguins Island - Website
    url: https://waddlepenguins.me/
  - name: Waddle Penguins Island - API
    url: https://api.waddlepenguins.me/
  - name: Waddle Penguins Island - Game Server
    url: $GAMESERVER_URL
  - name: Waddle Penguins Island - Content
    url: https://cdn.waddlepenguins.me/
    expectedStatusCodes:
      - 200
      - 403
      - 404
  - name: CDN
    url: https://cdn.fullmoon.dev/
  - name: Archive
    url: https://archive.dink.cf/
    expectedStatusCodes:
      - 200
      - 404
      - 401
  - name: Club Penguin Atake - Website
    url: https://cpatake.boo/
  - name: Club Penguin Atake - AS1
    url: https://as1.cpatake.boo/
  - name: Club Penguin Atake - AS2
    url: https://as2.cpatake.boo/
  - name: Club Penguin Atake - AS3
    url: https://as3.cpatake.boo/
  - name: Club Penguin Atake - Client 5.0
    url: https://butterfly.cpatake.boo/
    headers:
    - "User-Agent: $CLUBPENGUINATAKE_CLIENTBUTTERFLY_STATUSAGENT"
  - name: Club Penguin Atake - Web Client
    url: https://web.cpatake.boo/
  - name: Club Penguin Atake TV
    url: https://tv.cpatake.boo/
  - name: Club Penguin Atake Radio
    url: https://www.cpatake.boo/radio/
  - name: Club Penguin Atake E-Reader
    url: https://www.cpatake.boo/e-reader/
  - name: Club Penguin Atake TV Video CDN
    url: https://cdn.tv.cpatake.boo/
    expectedStatusCodes:
      - 200
      - 403
      - 401
  - name: Club Penguin Atake Radio Audio CDN
    url: https://cdn.media-radio.cpatake.tk/
    expectedStatusCodes:
      - 200
      - 403
      - 401

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fullmoon.dev
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.fullmoon.dev/images/moonlight/square.png
  name: Moonlight Status
  introTitle: "Welcome to the Status page of all Moonlight Studios services."
  introMessage: Check the status of your favourite services here.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
