# Change these first
owner: MoonlightStudiosInt # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Waddle Penguins Island - Website
    url: https://waddlepenguins.me/
  - name: Waddle Penguins Island - API
    url: https://api.waddlepenguins.me/
  - name: Waddle Penguins Island - Game Server
    url: $GAMESERVER_URL
  - name: Waddle Penguins Island - Content
    url: https://cdn.waddlepenguins.me/
    expectedStatusCodes:
      - 200
      - 403
  - name: Files 2 Server
    url: https://files2.dink.cf/
  - name: Files 3 Server
    url: https://files3.dink.cf/
  - name: Moonlight Studios Archive
    url: https://archive.dink.cf/
    expectedStatusCodes:
      - 200
      - 404
      - 403
  - name: Club Penguin Atake - Website
    url: https://cpatake.dink.cf/
  - name: Club Penguin Atake - AS1
    url: https://as1-cpa.dink.cf/
  - name: Club Penguin Atake - AS2
    url: https://as2-cpa.dink.cf/
  - name: Club Penguin Atake - AS2 (CC)
    url: https://web.cpatake.dink.cf/cppscreator
  - name: Club Penguin Atake - AS3
    url: https://as3-cpa.dink.cf/
  - name: Club Penguin Atake - Client 4.0
    url: $CLUBPENGUINATAKE_CLIENTBUTTERFLY_URL
    headers:
    - "User-Agent: $CLUBPENGUINATAKE_CLIENTBUTTERFLY_STATUSAGENT"
  - name: Club Penguin Atake - Web Client
    url: https://web.cpatake.dink.cf/
  - name: Club Penguin Atake TV
    url: https://cpataketv.dink.cf/
  - name: Club Penguin Atake TV Video CDN
    url: https://cdn.cpataketv.dink.cf/
    expectedStatusCodes:
      - 200
      - 403
      - 401
  - name: Club Penguin Atake TV Images CDN
    url: https://cdn-images.cpataketv.dink.cf/
    expectedStatusCodes:
      - 200
      - 403
  - name: Club Penguin Atake TV Edge Captions
    url: https://captions.cpataketv.dink.cf/
    expectedStatusCodes:
      - 200
      - 403
  - name: Club Penguin Elemental
    url: https://cpelemental.dink.cf/
  - name: Club Penguin Elemental Client
    url: https://cpelemental-client.dink.cf/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.dink.cf
  # baseUrl: /your-repo-name
  logoUrl: https://files3.dink.cf/images/moonlight/square.png
  name: Moonlight Status
  introTitle: "Welcome to the Status page of all Moonlight Studios services."
  introMessage: Check the status of your favourite services here.
  navbar:
    - title: Status
      href: /
    - title: Waddle Penguins Island
      href: https://waddlepenguins.me/?from=status.dink.cf
    - title: Club Penguin Atake
      href: https://cpatake.dink.cf/?from=status.dink.cf
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
